# Netlify configuration for Nilu Tourism Platform Frontend

[build]
  # Build command
  command = "npm run build"

  # Directory with the build output
  publish = "dist"

  # Base directory for the build
  base = "frontend"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set these in Netlify UI)
# VITE_API_URL = your backend URL (e.g., https://your-backend.railway.app)

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Build settings
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Deploy previews configuration
[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Production-specific settings
[context.production]
  command = "npm run build"
